server:
    port: 59527

#network
network:
    url:
        landing: html/landing.html
        test: html/test_upload.html
        index: index.html

path:
    data: /data/

#log
logging:
    path: ./logs/
    file:
        max-size: 30MB
        max-history: 3

